id = "golangci-lint"
name = "Golangci-Lint"
description = "Golangci Lint support."
version = "0.1.1"
schema_version = 1
authors = ["Jordan Gregory <jordan@j4ng5y.dev>", "Scott Nicol <s@ncl.im>"]
repository = "https://github.com/snicol/zed_golangci_lint"

[language_servers.golangci-lint]
name = "golangci-lint"
language = "Golangci Lint"
languages = ["Go"]
